version: 2
jobs:

  dashing:
    docker:
      - image: ros:dashing-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq && apt-get install -y python3-colcon-common-extensions
            source /opt/ros/dashing/setup.bash
            mkdir temp_$CIRCLE_PROJECT_REPONAME
            mv `find -maxdepth 1 -not -name . -not -name temp_$CIRCLE_PROJECT_REPONAME` temp_$CIRCLE_PROJECT_REPONAME/
            mv temp_$CIRCLE_PROJECT_REPONAME/ $CIRCLE_PROJECT_REPONAME/
            rosdep install --from-paths . --ignore-src -y
            cd ..
      - run:
          name: Build
          command: |
            source /opt/ros/dashing/setup.bash
            cd ..
            colcon build
      - run:
          name: Run Tests
          command: |
            source /opt/ros/dashing/setup.bash
            cd ..
            colcon test
            colcon test-result --verbose
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - dashing
